using System;

namespace CCC_API.Data.Responses.Settings.KeywordSearches
{
    public class MediaMonitorKeywordSearch
    {

        public string mediaMonitorId { get; set; }
        public string name { get; set; }
        public int newsSourceId { get; set; }
        public int companyId { get; set; }
        public int dataGroupId { get; set; }
        public string searchClause { get; set; }
        public Boolean active { get; set; }
        public Boolean includeInAnalytics { get; set; }
        public int version { get; set; }
        public string lastSearchDate { get; set; }
        public int currentSearchCount { get; set; }
        public int maximumSearchCount { get; set; }
        public int lastSearchDuration { get; set; }
        public string lastSearchSql { get; set; }
        public string languageIDs { get; set; }
        public string countryIDs { get; set; }
        public string continentIDs { get; set; }
        public string creationDate { get; set; }
        public string lastModifiedDate { get; set; }
        public string mediaOutletListIDs { get; set; }
        public string outletSearchOption { get; set; }
        public string searchClauseWithAll { get; set; }
        public string searchClauseWithAny { get; set; }
        public string searchClauseWithOut { get; set; }
        public string newsOnDemandSourceIDs { get; set; }
        public string lastArchiveDate { get; set; }
        public string archivePopulateStartDate { get; set; }
        public int searchType { get; set; }
        public Boolean isAutoGenerated { get; set; }
        public string newsOnDemandSearchSubjectExclusionIDs { get; set; }
        public MediaMonitorKeywordSearch() { }

    }
}
